assignment/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('online/', include("online.urls"))
]

online/urls.py
from django.urls import path
from . import views

app_name = "online"
urlpatterns = [
    path("", views.auth_view, name='login'),

]

online/models.py
from django.db import models


# Create your models here.
class Question(models.Model):
    question = models.CharField(max_length=150)
    answer = models.CharField(max_length=150)
    category = models.CharField(max_length=150)


class Choices(models.Model):
    question = models.ForeignKey("Question", related_name="choices" , on_delete=models.CASCADE)
    choice = models.CharField("choice", max_length=50,)
    position = models.IntegerField("position")

    class Meta:
        unique_together = [
            ("question", "choice"),
            ("question", "position")
        ]
        ordering = ("position",)

online/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User


class RegesterForm(ModelForm):
    class Meta:
        model = User
        exclude = ['is_staff', 'is_superuser', 'is_active']

online/views.py
from django.shortcuts import render, redirect
from .models import Question, Choices
from django.contrib import auth, messages
from django.contrib.auth import authenticate
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView
from django.template.context_processors import csrf
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.tokens import default_token_generator
from django.db import connection
from .forms import RegesterForm


# Create your views here.
def auth_view(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    user = auth.authenticate(username=username, password=password)

    if user is not None:
        auth.login(request, user)
        return HttpResponseRedirect('/home/ home')
    else:
        messages.info("Invalid Username or Password")
        return HttpResponseRedirect('/online/login_user')


@login_required(login_url='/online/login_user')
def invalid_login(request):
    return render(request, 'login.html', context=None)


@login_required(login_url='/online/login_user')
def logged_in(request):
    return render(request, '/home/home', {'full_name': request.user.username})


@login_required(login_url='/online/login_user')
def logout(request):
    auth.logout(request)
    return render(request, 'logout.html', context=None)


class NewUserPage(TemplateView):
    def get(self, request, **kwargs):
        return render(request, 'new_user.html', context=None)


def register(request):
    form = RegesterForm(request.POST)
    if form.is_valid():
        user = form.save()
        request.session['username'] = request.POST.get('username', '')
        auth.login(request, user, backend='django.contrib.auth.backends.ModelBackend')
        return redirect('/home/home')
    return render(request, 'new_user.html', {'form': form})


class UserPage(TemplateView):
    def get(self, request, **kwargs):
        return render(request, 'neww.html', context=None)


def lostPassword(request):
    return render(request, 'neww.html', context=None)


@login_required(login_url='/online/login')
def quiz_myth(request):
    data = Question.objects.raw("select * from online_question where category == 'myth';")
    opts = Question.objects.raw("select * from online_choice;")
    return render(request, 'quizM.html', {'data': data, 'opts': opts})


@login_required(login_url='/online/login')
def quiz_myth1(request):
    data1 = Question.objects.raw("sect * from online_question;")
    opts1 = Question.objects.raw("select * from online_choice;")
    return render(request, 'quizM1.html',{'data1': data1, 'opts1': opts1})

online/templates/login.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<!DOCTYPE html>
<html>

<head>
	<title>My Awesome Login Page</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
</head>
<!--Coded with love by Mutiullah Samim-->
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<div class="brand_logo_container">
						<img src="https://cdn.freebiesupply.com/logos/large/2x/pinterest-circle-logo-png-transparent.png" class="brand_logo" alt="Logo" height="100px" width="100px">
					</div>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form action="{% url 'online:login' %}" method="post">
                    {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" class="form-control input_user" value="" placeholder="username">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							<input type="password" name="password" class="form-control input_pass" value="" placeholder="password">
						</div>
						<div class="form-group">
							<div class="custom-control custom-checkbox">
								<input type="checkbox" class="custom-control-input" id="customControlInline">
								<label class="custom-control-label" for="customControlInline">Remember me</label>
							</div>
						</div>
							<div class="d-flex justify-content-center mt-3 login_container">
				 	<button type="button" name="button" class="btn login_btn">Login</button>
				   </div>
					</form>
				</div>

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="#" class="ml-2">Sign Up</a>
					</div>
					<div class="d-flex justify-content-center links">
						<a href="#">Forgot your password?</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>